import type { AdminSiteConfig, ThemeTokens } from './types';
import { categories, allProducts, epicDeals, brandLogosList } from '../data/products';

export const defaultThemeTokens: ThemeTokens = {
  colorPrimary: '#7C3AED',
  colorPrimaryHover: '#6D28D9',
  colorSecondary: '#15803D',
  colorSecondaryHover: '#166534',
  colorAccent: '#EA580C',
  colorBackground: '#F8FAFC',
  colorSurface: '#FFFFFF',
  colorTextPrimary: '#0F172A',
  colorTextMuted: '#64748B',
  colorBorder: '#E2E8F0',

  headerBackground: '#FFFFFF',
  headerTextColor: '#0F172A',
  headerSearchBorder: '#E2E8F0',
  headerSearchFocus: '#8B5CF6',
  navbarBackground: '#EDE9FE',
  navbarBorderColor: '#DDD6FE',
  navbarTextColor: '#5B21B6',
  navbarActiveColor: '#6D28D9',
  navbarCategoriesBtnBg: '#DCFCE7',
  navbarCategoriesBtnText: '#15803D',

  heroBackground: '#F3E8FF',
  heroBorderColor: '#EDE9FE',

  btnPrimaryBg: '#7C3AED',
  btnPrimaryText: '#FFFFFF',
  btnPrimaryHoverBg: '#6D28D9',
  btnSecondaryBg: '#DCFCE7',
  btnSecondaryText: '#15803D',
  btnAccentBg: '#EA580C',
  btnAccentText: '#FFFFFF',

  cardBg: '#FFFFFF',
  cardBorder: '#F1F5F9',
  cardShadow: '0 4px 18px rgba(0, 0, 0, 0.06)',
  cardPriceColor: '#7C3AED',

  dealsBannerBgStart: '#4C1D95',
  dealsBannerBgMiddle: '#5B21B6',
  dealsBannerBgEnd: '#3B0764',
  dealsNeonBadgeBg: '#0F172A',
  dealsNeonBadgeBorder: '#FACC15',
  dealsNeonBadgeText: '#FDE047',

  footerBg: '#0F172A',
  footerTextColor: '#94A3B8',
  footerHeadingColor: '#FFFFFF',
  footerLinkColor: '#CBD5E1',
  footerLinkHover: '#C4B5FD',
  footerBorderColor: '#1E293B',

  statusSuccess: '#16A34A',
  statusWarning: '#D97706',
  statusError: '#DC2626',
  statusInfo: '#2563EB',
};

export const defaultSiteConfig: AdminSiteConfig = {
  theme: defaultThemeTokens,
  sectionOrder: [
    { id: 'hero', name: 'Hero Banner', enabled: true, order: 1 },
    { id: 'brandMarquee', name: 'Trusted Brands Marquee', enabled: true, order: 2 },
    { id: 'featureStrip', name: 'Top 5 Feature Strip', enabled: true, order: 3 },
    { id: 'categorySection', name: 'Shop by Category', enabled: true, order: 4 },
    { id: 'popularProducts', name: 'Popular Today ⚡', enabled: true, order: 5 },
    { id: 'epicDeals', name: 'Epic Deals All Day', enabled: true, order: 6 },
    { id: 'futureArrivals', name: 'Future Arrivals', enabled: true, order: 7 },
    { id: 'bottomFeatureStrip', name: 'Bottom Benefits Strip', enabled: true, order: 8 },
  ],
  topOfferBar: {
    enabled: true,
    leftTextPrefix: '10% OFF on your first order | Use code: ',
    discountHighlight: '10% OFF',
    leftTextSuffix: ' on your first order | Use code:',
    promoCode: 'FARM10',
    downloadAppText: 'Download App',
    trackOrderText: 'Track Order',
    helpText: 'Help',
    appStoreAlertMessage: 'Farminix Mobile App available on iOS App Store & Google Play Store!',
  },
  header: {
    enabled: true,
    logoUrl: '/farminix_logo.png',
    logoAlt: 'Farminix Logo',
    deliveryLabel: 'Deliver to',
    searchPlaceholders: [
      'Search for rice, atta, oil, dal...',
      'Try "Daawat Basmati Rice"...',
      'Search for masala, spices...',
      'Try "Amul Butter"...',
      'Search for dals & pulses...',
      'Try "Aashirvaad Atta 5kg"...',
      'Search for snacks & beverages...',
      'Try "Fortune Sunflower Oil"...',
      'Search for household essentials...',
      'Try "Tata Salt 1kg"...',
    ],
    loginButtonText: 'Login / Sign up',
    cartButtonText: 'Cart',
  },
  navItems: [
    { id: 'nav-1', label: 'Home', catId: null, enabled: true, order: 1 },
    { id: 'nav-2', label: 'Dals & Pulses', catId: 'dals', enabled: true, order: 2 },
    { id: 'nav-3', label: 'Rice & Grains', catId: 'rice', enabled: true, order: 3 },
    { id: 'nav-4', label: 'Atta & Flours', catId: 'atta', enabled: true, order: 4 },
    { id: 'nav-5', label: 'Oils & Ghee', catId: 'oils', enabled: true, order: 5 },
    { id: 'nav-6', label: 'Masala & Spices', catId: 'masala', enabled: true, order: 6 },
    { id: 'nav-7', label: 'Snacks & Beverages', catId: 'snacks', enabled: true, order: 7 },
    { id: 'nav-8', label: 'Household', catId: 'household', enabled: true, order: 8 },
    { id: 'nav-9', label: 'Offers', catId: 'offers', badge: 'HOT', enabled: true, order: 9 },
  ],
  hero: {
    enabled: true,
    bannerImage: '/hero_banner_original.jpg',
    altText: 'Farminix Fresh Groceries',
    shopNowUrl: '/products',
    homeUrl: '/',
  },
  brandMarquee: {
    enabled: true,
    badgeText: 'Our Partners',
    title: 'Trusted Brands We Carry',
    description: "Authentic products from India's most loved brands — straight to your door.",
    brands: brandLogosList.map((b, idx) => ({
      id: `b-${idx + 1}`,
      name: b.name,
      logo: b.logo,
      enabled: true,
      order: idx + 1,
    })),
  },
  featureStrip: {
    enabled: true,
    features: [
      { id: 1, iconName: 'Zap', title: '10 Min Delivery', subtitle: 'Super Fast', bgColor: 'bg-purple-100', enabled: true, order: 1 },
      { id: 2, iconName: 'ShieldCheck', title: 'Quality Assured', subtitle: '100% Genuine', bgColor: 'bg-emerald-100', enabled: true, order: 2 },
      { id: 3, iconName: 'IndianRupee', title: 'Best Prices', subtitle: 'Direct from Brands', bgColor: 'bg-purple-100', enabled: true, order: 3 },
      { id: 4, iconName: 'Lock', title: 'Safe & Secure', subtitle: 'Secure Packaging', bgColor: 'bg-emerald-100', enabled: true, order: 4 },
      { id: 5, iconName: 'Headset', title: '24/7 Support', subtitle: 'We are here for you', bgColor: 'bg-amber-100', actionType: 'support', enabled: true, order: 5 },
    ],
  },
  categorySection: {
    enabled: true,
    title: 'Shop by Category',
    seeAllText: 'See All',
    seeAllUrl: '/products',
  },
  categories: categories,
  popularProducts: {
    enabled: true,
    title: 'Popular Today',
    viewAllText: 'View All',
    viewAllUrl: '/products',
    badgeIcon: '⚡',
    featuredProductIds: ['r1', 'a1', 'o1', 'ss1', 'd1', 'm1'],
  },
  epicDeals: {
    enabled: true,
    topPillText: 'ZERO GRAVITY SAVINGS',
    mainTitle: 'EPIC DEALS',
    subTitle: 'ALL DAY',
    deals: epicDeals,
  },
  futureArrivals: {
    enabled: true,
    title: 'Future Arrivals',
    subtitle: 'Premium choices coming soon to Farminix',
    items: [
      { id: 1, name: 'Fresh Fruits', image: 'https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?auto=format&fit=crop&q=80&w=300', badgeText: 'Coming Soon', enabled: true, order: 1 },
      { id: 2, name: 'Fresh Vegetables', image: 'https://images.unsplash.com/photo-1597362925123-77861d3fbac7?auto=format&fit=crop&q=80&w=300', badgeText: 'Coming Soon', enabled: true, order: 2 },
      { id: 3, name: 'Dairy Products', image: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&q=80&w=300', badgeText: 'Coming Soon', enabled: true, order: 3 },
      { id: 4, name: 'Dry Fruits', image: 'https://images.unsplash.com/photo-1596547609652-9cf5d8d76921?auto=format&fit=crop&q=80&w=300', badgeText: 'Coming Soon', enabled: true, order: 4 },
      { id: 5, name: 'Cooking Oils', image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&q=80&w=300', badgeText: 'Coming Soon', enabled: true, order: 5 },
      { id: 6, name: 'Organic Products', image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=80&w=300', badgeText: 'Coming Soon', enabled: true, order: 6 },
      { id: 7, name: 'Ready-to-Cook Products', image: 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=300', badgeText: 'Coming Soon', enabled: true, order: 7 },
    ],
  },
  bottomFeatureStrip: {
    enabled: true,
    boxes: [
      { id: 1, iconName: 'Package', title: 'No Minimum Order', subtitle: 'Order any quantity', bgColor: 'bg-emerald-100', enabled: true, order: 1 },
      { id: 2, iconName: 'RefreshCw', title: 'Easy Returns & Refunds', subtitle: 'Hassle free returns', bgColor: 'bg-emerald-100', enabled: true, order: 2 },
      { id: 3, iconName: 'Headset', title: '24/7 Customer Support', subtitle: 'We are here for you', bgColor: 'bg-amber-100', actionType: 'support', enabled: true, order: 3 },
      { id: 4, iconName: 'ShieldCheck', title: '100% Quality Assured', subtitle: 'Genuine products only', bgColor: 'bg-purple-100', enabled: true, order: 4 },
    ],
  },
  footer: {
    enabled: true,
    logoUrl: '/farminix_logo.png',
    bioText: 'Your trusted partner for quality groceries. Fresh produce, authentic staples, and instant 10-minute home delivery.',
    socialLinks: {
      instagram: '#',
      facebook: '#',
      twitter: '#',
      youtube: '#',
    },
    companyLinks: [
      { id: 'c1', label: 'About Us', url: '#' },
      { id: 'c2', label: 'Career', url: '#' },
      { id: 'c3', label: 'Blog', url: '#' },
      { id: 'c4', label: 'Contact Us', url: '#', actionType: 'support' },
    ],
    helpLinks: [
      { id: 'h1', label: 'FAQs', url: '#', actionType: 'support' },
      { id: 'h2', label: 'Shipping & Delivery', url: '#' },
      { id: 'h3', label: 'Returns & Refunds', url: '#' },
      { id: 'h4', label: 'Terms & Conditions', url: '#' },
    ],
    downloadApp: {
      googlePlayUrl: '#',
      appleAppStoreUrl: '#',
    },
    legalLinks: [
      { id: 'l1', label: 'Privacy Policy', url: '#' },
      { id: 'l2', label: 'Cancellation Policy', url: '#' },
      { id: 'l3', label: 'Refund Policy', url: '#' },
      { id: 'l4', label: 'Disclaimer', url: '#' },
    ],
    copyrightText: '© 2025 Farminix. All rights reserved.',
  },
  offersPage: {
    enabled: true,
    heroBadge: 'MEGA SAVINGS FESTIVAL',
    heroTitle: 'Zero Gravity Savings',
    heroSubtitle: 'Handpicked grocery deals with guaranteed lowest prices and 10-minute doorstep delivery.',
    countdownHours: 18,
    promoCode: 'FARM10',
  },
  products: allProducts,
  orders: [
    {
      id: 'ORD-89241',
      date: new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric' }),
      items: [{ product: allProducts[0], quantity: 1, selectedWeight: '1 kg' }],
      totalAmount: 209,
      discount: 21,
      deliveryFee: 0,
      finalAmount: 188,
      status: 'Out for Delivery',
      estimatedTime: '8 Mins',
      deliveryAddress: {
        id: 'addr-1',
        name: 'Hitaishi Devarapalli',
        street: 'Plot No. 42, Brodipet 4th Line',
        city: 'Guntur',
        state: 'Andhra Pradesh',
        pincode: '522034',
        phone: '+91 98765 43210',
        isDefault: true,
      },
      paymentMethod: 'UPI',
    },
    {
      id: 'ORD-77412',
      date: '12 Aug 2026',
      items: [{ product: allProducts[1], quantity: 2, selectedWeight: '1 kg' }],
      totalAmount: 370,
      discount: 37,
      deliveryFee: 0,
      finalAmount: 333,
      status: 'Delivered',
      estimatedTime: 'Delivered',
      deliveryAddress: {
        id: 'addr-1',
        name: 'Hitaishi Devarapalli',
        street: 'Plot No. 42, Brodipet 4th Line',
        city: 'Guntur',
        state: 'Andhra Pradesh',
        pincode: '522034',
        phone: '+91 98765 43210',
        isDefault: true,
      },
      paymentMethod: 'CARD',
    },
  ],
  users: [
    {
      id: 'usr-1',
      name: 'Hitaishi Devarapalli',
      phone: '+91 98765 43210',
      email: 'hitaishi@example.com',
      rewardPoints: 350,
      walletBalance: 250,
      addresses: [
        {
          id: 'addr-1',
          name: 'Hitaishi Devarapalli',
          street: 'Plot No. 42, Brodipet 4th Line',
          city: 'Guntur',
          state: 'Andhra Pradesh',
          pincode: '522034',
          phone: '+91 98765 43210',
          isDefault: true,
        },
      ],
    },
  ],
  mediaLibrary: [
    { id: 'med-1', name: 'Farminix Main Logo', url: '/farminix_logo.png', category: 'brand', uploadedAt: '2026-08-10', size: '728 KB' },
    { id: 'med-2', name: 'Hero Banner Image', url: '/hero_banner_original.jpg', category: 'banner', uploadedAt: '2026-08-10', size: '1.9 MB' },
    { id: 'med-3', name: 'Daawat Basmati Rice Pack', url: '/prod_daawat_rice.jpg', category: 'product', uploadedAt: '2026-08-10', size: '522 KB' },
    { id: 'med-4', name: 'Aashirvaad Atta Pack', url: '/prod_aashirvaad_atta.jpg', category: 'product', uploadedAt: '2026-08-10', size: '624 KB' },
    { id: 'med-5', name: 'Fortune Oil Pack', url: '/prod_fortune_oil.jpg', category: 'product', uploadedAt: '2026-08-10', size: '444 KB' },
    { id: 'med-6', name: 'Tata Salt Pack', url: '/prod_tata_salt.jpg', category: 'product', uploadedAt: '2026-08-10', size: '541 KB' },
    { id: 'med-7', name: 'Dals Category Image', url: '/cat_dals.jpg', category: 'category', uploadedAt: '2026-08-10', size: '557 KB' },
    { id: 'med-8', name: 'Rice Category Image', url: '/cat_rice.jpg', category: 'category', uploadedAt: '2026-08-10', size: '495 KB' },
    { id: 'med-9', name: 'Atta Category Image', url: '/cat_atta.jpg', category: 'category', uploadedAt: '2026-08-10', size: '606 KB' },
    { id: 'med-10', name: 'Oils Category Image', url: '/cat_oils.jpg', category: 'category', uploadedAt: '2026-08-10', size: '495 KB' },
    { id: 'med-11', name: 'Masala Category Image', url: '/cat_masala.jpg', category: 'category', uploadedAt: '2026-08-10', size: '595 KB' },
    { id: 'med-12', name: 'Snacks Category Image', url: '/cat_snacks.jpg', category: 'category', uploadedAt: '2026-08-10', size: '573 KB' },
    { id: 'med-13', name: 'Household Category Image', url: '/cat_household.jpg', category: 'category', uploadedAt: '2026-08-10', size: '489 KB' },
    { id: 'med-14', name: 'Sugar & Salt Category Image', url: '/cat_sugar_salt.jpg', category: 'category', uploadedAt: '2026-08-10', size: '514 KB' },
  ],
};
